### ISSUE TITLE
Add GitHub actions to close issues/pull requests

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#435]
In our [contributing](https://github.com/tempestphp/tempest-framework/blob/main/.github/CONTRIBUTING.md#report-an-error-or-bug) guide, we articulate that issues will be closed after 30 days of no response. We should setup some GitHub actions to enforce this across issues and pull requests.

**Comment by ericsizemore** [comment]
Could probably come up with something using [actions/stale](https://github.com/marketplace/actions/close-stale-issues). 

If you all are good with using this particular action, the workflow would be rather simple:

```yaml
name: "Close stale issues/pull requests."
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 1
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 30 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 1 day since being marked as stale."
          stale-pr-label: "stale"
          stale-pr-message: "This pull request is stale because it has been open for 30 days with no activity."
          close-pr-message:  "This pull request was closed because it has been inactive for 1 day since being marked as stale."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

There are [several options](https://github.com/marketplace/actions/close-stale-issues#repo-token) available. You can set different stale/close days for issues and PRs, or the same number of days (as is done above). Could whip up a PR for this if anyone has any recommendations on the messages used, or any other particular options/settings for the action.
